# Generated by Django 5.0.6 on 2024-07-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recorridos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('estado', models.TextField(max_length=15)),
                ('ciudad', models.TextField()),
                ('km_recorrido', models.FloatField()),
                ('tiempo_estimado', models.TimeField()),
                ('punto_inicio', models.TextField()),
                ('costo', models.IntegerField()),
                ('foto_zona_visitar', models.TextField()),
                ('activo', models.BooleanField(verbose_name=True)),
            ],
        ),
    ]
