# Generated by Django 5.0.6 on 2024-08-15 06:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recorridos',
            fields=[
                ('id_recorrido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(verbose_name='Fecha del recorrido')),
                ('horaSalida', models.TimeField(verbose_name='Hora de partida')),
                ('horaLlegada', models.TimeField(verbose_name='Hora de llegada')),
                ('estado', models.CharField(max_length=70)),
                ('ciudad', models.CharField(max_length=70)),
                ('km_recorrido', models.FloatField(verbose_name='Kilómetros')),
                ('tiempo_estimado', models.TimeField(verbose_name='Tiempo estimado en horas')),
                ('descripcion', models.TextField(max_length=200, verbose_name='Agrega una descripción del recorrido')),
                ('punto_inicio', models.TextField(max_length=200)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Costo')),
                ('foto_zona_visitar', models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografía')),
                ('activo', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recorrido',
                'verbose_name_plural': 'Recorridos',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id_inscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_nombre', models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')], verbose_name='Nombre:')),
                ('usuario_correo_electronico', models.EmailField(db_index=True, max_length=80, validators=[django.core.validators.EmailValidator()], verbose_name='Correo electronico:')),
                ('usuario_telefono', models.CharField(db_index=True, max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)], verbose_name='Telefono:')),
                ('usuario_ciudad', models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')], verbose_name='Ciudad:')),
                ('usuario_estado', models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')], verbose_name='Estado:')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_recorrido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recorridos.recorridos', verbose_name='Recorridos')),
            ],
            options={
                'verbose_name': 'Inscripcion',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField()),
                ('calificacion', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(5), django.core.validators.MinLengthValidator(1)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recorridos.inscripcion', verbose_name='Inscripcion')),
                ('id_recorrido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recorridos.recorridos', verbose_name='Recorrido')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['created'],
            },
        ),
    ]
