# Generated by Django 5.0.6 on 2024-08-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorridos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recorridos',
            old_name='horaSalida',
            new_name='hora',
        ),
        migrations.RemoveField(
            model_name='recorridos',
            name='horaLlegada',
        ),
        migrations.AlterField(
            model_name='recorridos',
            name='fecha',
            field=models.DateField(verbose_name='Fecha del recorrido'),
        ),
        migrations.AlterField(
            model_name='recorridos',
            name='punto_inicio',
            field=models.TextField(max_length=200, verbose_name='Punto de reunión'),
        ),
    ]
