# Generated by Django 5.0.6 on 2024-07-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorridos', '0002_alter_recorridos_options_recorridos_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorridos',
            name='foto_zona_visitar',
            field=models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografía'),
        ),
    ]
