# Generated by Django 5.0.6 on 2024-07-09 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorridos', '0003_alter_recorridos_foto_zona_visitar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recorridos',
            name='id',
        ),
        migrations.AddField(
            model_name='recorridos',
            name='id_recorrido',
            field=models.CharField(default='DEFAULT_ID', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recorridos',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recorridos',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id_inscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_nombre', models.CharField(max_length=255)),
                ('usuario_correo_electronico', models.CharField(max_length=255)),
                ('usuario_telefono', models.CharField(max_length=20)),
                ('usuario_ciudad', models.CharField(max_length=255)),
                ('usuario_estado', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_recorrido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recorridos.recorridos')),
            ],
            options={
                'verbose_name': 'Inscripcion',
                'verbose_name_plural': 'Inscripciones',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_comentario', models.CharField(max_length=255)),
                ('comentario', models.TextField()),
                ('calificacion', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id_recorrido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recorridos.recorridos')),
                ('id_inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recorridos.inscripcion')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
            },
        ),
    ]
