# Generated by Django 5.0.6 on 2024-07-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorridos', '0004_remove_recorridos_id_recorridos_id_recorrido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorridos',
            name='id_recorrido',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
