# Generated by Django 5.0.6 on 2024-07-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorridos', '0005_alter_recorridos_id_recorrido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='usuario_ciudad',
            field=models.CharField(max_length=255, verbose_name='Ciudad:'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='usuario_correo_electronico',
            field=models.CharField(max_length=255, verbose_name='Correo electronico:'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='usuario_estado',
            field=models.CharField(max_length=255, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='usuario_nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre:'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='usuario_telefono',
            field=models.CharField(max_length=20, verbose_name='Telefono:'),
        ),
    ]
