# Generated by Django 5.0.6 on 2024-07-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorridos', '0006_alter_inscripcion_usuario_ciudad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='id',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='id_comentario',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
