# Generated by Django 5.0.6 on 2024-07-09 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recorridos', '0007_remove_comentario_id_alter_comentario_id_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-created'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'ordering': ['-created'], 'verbose_name': 'Inscripcion', 'verbose_name_plural': 'Inscripciones'},
        ),
    ]
