# Generated by Django 5.0.6 on 2024-07-09 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recorridos', '0008_alter_comentario_options_alter_inscripcion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['created'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'ordering': ['created'], 'verbose_name': 'Inscripcion', 'verbose_name_plural': 'Inscripciones'},
        ),
        migrations.AlterModelOptions(
            name='recorridos',
            options={'ordering': ['created'], 'verbose_name': 'Recorrido', 'verbose_name_plural': 'Recorridos'},
        ),
    ]
