# Generated by Django 5.0.6 on 2024-07-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorridos', '0009_alter_comentario_options_alter_inscripcion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='id',
            field=models.BigAutoField(auto_created=True, default=5, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='id_comentario',
            field=models.CharField(max_length=255),
        ),
    ]
