# Generated by Django 5.0.6 on 2024-08-07 23:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorridos', '0010_comentario_id_alter_comentario_id_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='usuario_ciudad',
            field=models.CharField(max_length=60, verbose_name='Ciudad:'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='usuario_correo_electronico',
            field=models.EmailField(max_length=80, validators=[django.core.validators.EmailValidator()], verbose_name='Correo electronico:'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='usuario_estado',
            field=models.CharField(max_length=60, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='usuario_nombre',
            field=models.CharField(max_length=60, verbose_name='Nombre:'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='usuario_telefono',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)], verbose_name='Telefono:'),
        ),
    ]
