# Generated by Django 5.0.6 on 2024-08-07 23:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorridos', '0011_alter_inscripcion_usuario_ciudad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='id',
        ),
        migrations.AddField(
            model_name='comentario',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='calificacion',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(5), django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='id_comentario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='id_inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recorridos.inscripcion', verbose_name='Inscripcion'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='id_recorrido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recorridos.recorridos', verbose_name='Recorrido'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='id_recorrido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recorridos.recorridos', verbose_name='Recorridos'),
        ),
        migrations.AlterField(
            model_name='recorridos',
            name='id_recorrido',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
