# Generated by Django 5.0.6 on 2024-08-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorridos', '0012_remove_comentario_id_comentario_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorridos',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='recorridos',
            name='km_recorrido',
            field=models.FloatField(verbose_name='Kilómetros'),
        ),
        migrations.AlterField(
            model_name='recorridos',
            name='tiempo_estimado',
            field=models.TimeField(verbose_name='Tiempo estimado en horas'),
        ),
    ]
