# Generated by Django 5.0.6 on 2024-08-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorridos', '0013_alter_recorridos_costo_alter_recorridos_km_recorrido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorridos',
            name='ciudad',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='recorridos',
            name='estado',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='recorridos',
            name='punto_inicio',
            field=models.TextField(max_length=200),
        ),
    ]
