# Generated by Django 5.0.6 on 2024-08-10 22:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorridos', '0014_alter_recorridos_ciudad_alter_recorridos_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='usuario_correo_electronico',
            field=models.EmailField(db_index=True, max_length=80, validators=[django.core.validators.EmailValidator()], verbose_name='Correo electronico:'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='usuario_telefono',
            field=models.CharField(db_index=True, max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)], verbose_name='Telefono:'),
        ),
    ]
